# Generated by Django 4.2.2 on 2023-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0005_remove_cart_items_cart_created_at_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
